- name: Ensure Argo CD namespace exists
  kubernetes.core.k8s:
    # kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    api_version: v1
    kind: Namespace
    name: "{{ argocd_namespace }}"
    state: present
  # become: true
  # delegate_to: localhost
  # run_once: true
