
- name: Allow user to sudo without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ ansible_user }}
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    create: true
    state: present
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
  become: yes

- name: Install dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    # - git
    # - curl
    # - vim
    - python3-kubernetes 
    - htop
